language: node_js
node_js:
  - 10.16.3
cache:
  directories:
    - node_modules
script:
  - npm run test:unit
  - yarn build
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  skip-cleanup: true
  keep-history: false
  local-dir: dist
  repo: maslaknikolai/fastnote
  target-branch: master
  on:
    branch: master
